name: CI/CD counter app

on:
  push:
    branches: [ master ]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the docker_compose
      run: sudo apt update
      
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}         
          
        run: |
          cd .ssh
          git clone https://github.com/Cataluniat/sshkeys
          cataluniat
          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
          ssh -i ~/.ssh/aws ubuntu@54.237.56.140 '
            cd testcicd
            sudo apt update
            sudo apt install python3-pip
            pip install pipenv
            pip3 install pipenv
            sudo pipenv install
            pipenv install --system
            cd app
            python3 manage.py runserver 0.0.0.0:8000