name: CI/CD counter app

on:
  push:
    branches: [ master ]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the docker_compose
      run: sudo apt update
      
    - name: Buid the application
      run: apt update

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}         
          
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd testcicd
            sudo apt update
            sudo apt install python3-pip
            pip install pipenv
            pip3 install pipenv
            sudo pipenv install
            pipenv install --system
            cd app
            python3 manage.py runserver 0.0.0.0:8000
